# Generated by Django 5.0.8 on 2026-07-31 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Регистрационный номер')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('document_type', models.SlugField(verbose_name='Тип документа')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], db_index=True, default='normal', max_length=20, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_review', 'На согласовании'), ('returned', 'Возвращён'), ('approved', 'Согласован'), ('completed', 'Завершён'), ('overdue', 'Просрочен'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дедлайн')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Согласован')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Архивирован')),
                ('current_approval_step', models.PositiveIntegerField(blank=True, null=True, verbose_name='Текущий шаг согласования')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Категория')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organizations.department', verbose_name='Подразделение')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_documents', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', 'status'], name='documents_d_author__c15f80_idx'), models.Index(fields=['department', 'status'], name='documents_d_departm_93cdc2_idx'), models.Index(fields=['responsible', 'status'], name='documents_d_respons_e2e68e_idx'), models.Index(fields=['category', 'status'], name='documents_d_categor_0ec696_idx')],
            },
        ),
    ]
