# Generated by Django 5.0.8 on 2026-07-31 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_counters', to='documents.documentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Счётчик номеров документов',
                'verbose_name_plural': 'Счётчики номеров документов',
            },
        ),
        migrations.AddConstraint(
            model_name='documentnumbercounter',
            constraint=models.UniqueConstraint(fields=('category', 'year'), name='unique_document_counter_category_year'),
        ),
    ]
