# Generated by Django 5.0.8 on 2026-07-31 17:56

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_seed_document_register_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.documents.models.document_file_upload_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя')),
                ('file_type', models.CharField(max_length=20, verbose_name='Тип файла')),
                ('mime_type', models.CharField(max_length=150, verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Загружен')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document', verbose_name='Документ')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл документа',
                'verbose_name_plural': 'Файлы документов',
                'ordering': ['-is_main', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('document',), name='unique_main_file_per_document'),
        ),
    ]
