# Generated by Django 5.0.8 on 2026-07-31 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_permissions_and_roles'),
        ('documents', '0005_documentfile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('returned', 'Возвращён'), ('cancelled', 'Отменён')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approval_routes', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_routes', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Маршрут согласования',
                'verbose_name_plural': 'Маршруты согласования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('current', 'Текущий'), ('approved', 'Согласован'), ('returned', 'Возвращён'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='documents.document', verbose_name='Документ')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to='accounts.role', verbose_name='Роль на момент назначения')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='documents.approvalroute', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Шаг согласования',
                'verbose_name_plural': 'Шаги согласования',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Согласовать'), ('return', 'Вернуть')], db_index=True, max_length=20, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='documents.document', verbose_name='Документ')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='documents.approvalstep', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Действие согласования',
                'verbose_name_plural': 'Действия согласования',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['document', 'status'], name='documents_a_documen_c29ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approver', 'status'], name='documents_a_approve_deb837_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('route', 'order'), name='unique_approval_step_order'),
        ),
    ]
