# Generated by Django 5.0.8 on 2026-07-31 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_approvalroute_approvalstep_approvalaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('comment_type', models.CharField(choices=[('general', 'Обычный'), ('approval', 'Комментарий согласования'), ('return_reason', 'Причина возврата'), ('system', 'Системный')], db_index=True, default='general', max_length=30, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Комментарий документа',
                'verbose_name_plural': 'Комментарии документов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Редактирование'), ('file_uploaded', 'Загрузка файла'), ('file_deleted', 'Удаление файла'), ('submitted', 'Отправка на согласование'), ('approved', 'Согласование'), ('returned', 'Возврат'), ('resubmitted', 'Повторная отправка'), ('registered', 'Регистрация'), ('completed', 'Завершение'), ('archived', 'Архивирование'), ('restored', 'Восстановление')], db_index=True, max_length=30, verbose_name='Действие')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Новые значения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История документа',
                'verbose_name_plural': 'История документов',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='documents_d_documen_d7392d_idx')],
            },
        ),
    ]
