# Generated by Django 5.0.8 on 2026-07-26 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('value_type', models.CharField(choices=[('string', 'Строка'), ('integer', 'Целое число'), ('boolean', 'Да/Нет'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Тип значения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, help_text='Публичные настройки видит любой авторизованный пользователь', verbose_name='Доступна всем пользователям')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Системная настройка',
                'verbose_name_plural': 'Системные настройки',
                'ordering': ['key'],
            },
        ),
    ]
