# Generated by Django 5.0.8 on 2026-07-26 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('login_failed', 'Неудачная попытка входа'), ('password_change', 'Смена пароля'), ('password_reset_request', 'Запрос восстановления пароля'), ('password_reset', 'Восстановление пароля'), ('profile_update', 'Изменение своего профиля'), ('user_create', 'Создание пользователя'), ('user_update', 'Изменение пользователя'), ('user_delete', 'Удаление пользователя'), ('user_block', 'Блокировка пользователя'), ('user_activate', 'Активация пользователя'), ('user_reset_password', 'Сброс пароля пользователя'), ('user_role_change', 'Изменение роли пользователя'), ('role_create', 'Создание роли'), ('role_update', 'Изменение роли'), ('role_delete', 'Удаление роли'), ('role_permissions_update', 'Изменение прав роли'), ('department_create', 'Создание подразделения'), ('department_update', 'Изменение подразделения'), ('department_delete', 'Удаление подразделения'), ('settings_update', 'Изменение системных настроек')], db_index=True, max_length=100, verbose_name='Действие')),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('result', models.CharField(choices=[('success', 'Успешно'), ('failure', 'Ошибка')], db_index=True, default='success', max_length=20, verbose_name='Результат')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
